name = "lingering-brook-95b4"
type = "javascript"
account_id = "86b5599ed346a176d5e582b1b1d92dc9"

# This field specifies that the Worker
# will be deployed to a *.workers.dev domain
workers_dev = true